name: Test-licz_sume

on:
  push:
    branches-ignore:
      - main
      - staging

permissions:
  contents: read

jobs:
  test_3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip pandas
    - name: Test-licz_sume
      run: |
        python test_3.py